"""Rendering and driving a launchd job — the primary target's supervisor.

Built with `plistlib` rather than a template string: the stdlib gets the
XML escaping right for free, and it gives the tests an exact round-trip
instead of a string comparison that passes for the wrong reason.
"""

from __future__ import annotations

import plistlib
from pathlib import Path
from typing import Any

from siteloom.service.spec import ServiceSpec

#: launchd has no comment field a tool can rely on reading back, so the
#: marker is an environment variable — functional as well as a label,
#: since it also tells the running process it was started by a unit.
MARKER_ENV = "SITELOOM_SERVICE_UNIT"

# XML forbids a double hyphen inside a comment, so this text says
# "a workers flag" where the systemd header can say the flag itself.
HEADER = (
    "<!-- Generated by `siteloom service install`. Edit the `service:`\n"
    "     section of the config and re-run install; `siteloom service\n"
    "     print-unit` shows this without writing it.\n"
    "\n"
    "     Do not add a uvicorn workers flag: the embedded Qdrant vector store\n"
    "     allows one client per path per machine. -->\n"
)


def agent_dir(scope: str) -> Path:
    """Where launchd looks. These paths are OS-defined — do not XDG them."""
    if scope == "system":
        return Path("/Library/LaunchDaemons")
    return Path.home() / "Library" / "LaunchAgents"


def unit_path(spec: ServiceSpec) -> Path:
    return agent_dir(spec.scope) / f"{spec.label}.plist"


def plist_dict(spec: ServiceSpec) -> dict[str, Any]:
    """The spec as launchd keys, before serialization."""
    data: dict[str, Any] = {
        "Label": spec.label,
        "ProgramArguments": list(spec.program),
        "WorkingDirectory": str(spec.working_dir),
        "EnvironmentVariables": dict(spec.environment),
        # For a LaunchAgent this means "at login", not "at boot" — the
        # CLI's summary says so rather than letting the flag name lie.
        "RunAtLoad": spec.start_at_boot,
        # launchd's TimeoutStopSec. Its own default is 20 s, which is
        # under what an in-flight commit batch can need.
        "ExitTimeOut": spec.stop_timeout_s,
    }
    if spec.restart == "always":
        data["KeepAlive"] = True
    elif spec.restart == "on-failure":
        # The direct analogue of Restart=on-failure. A bare `true` here —
        # what the hand-written template in the docs used to say — also
        # resurrects a server the operator stopped cleanly.
        data["KeepAlive"] = {"SuccessfulExit": False}
    if spec.restart != "never":
        # launchd complains below 10 and throttles anyway.
        data["ThrottleInterval"] = max(spec.restart_delay_s, 10)
    if spec.stdout_path is not None:
        data["StandardOutPath"] = str(spec.stdout_path)
    if spec.stderr_path is not None:
        data["StandardErrorPath"] = str(spec.stderr_path)
    # There is no ExecStartPre analogue, and wrapping the program in
    # `sh -c 'doctor && serve'` would put a shell between launchd and the
    # process it signals. So `spec.preflight` is unused here: `service
    # install` runs `doctor` itself instead, and the docs say plainly
    # that the macOS gate is at install time rather than at every start.
    #
    # ProcessType is deliberately absent. `Background` looks like the
    # right answer for a daemon and is not: it puts the job in a
    # throttled task-policy band that would starve YOLO inference on the
    # Apple Silicon target this project is built for. The default,
    # `Standard`, is what a video pipeline wants.
    return data


def render(spec: ServiceSpec) -> str:
    body = plistlib.dumps(plist_dict(spec), sort_keys=True).decode()
    # The comment goes after the XML declaration and DOCTYPE, which
    # plistlib emits as the first two lines.
    lines = body.splitlines(keepends=True)
    return "".join(lines[:2]) + HEADER + "".join(lines[2:])


def parse(text: str) -> dict[str, Any]:
    loaded = plistlib.loads(text.encode())
    assert isinstance(loaded, dict)
    return loaded
