"""Rendering and driving a systemd unit.

`render` is pure: spec in, unit text out. Everything that touches the
filesystem or `systemctl` is a method on the backend, which takes an
injectable runner — so the interesting half is testable on a machine
with no systemd at all.
"""

from __future__ import annotations

import os
from pathlib import Path

from siteloom.service.spec import ServiceSpec

#: `X-` keys are ignored by systemd without a warning, which makes them
#: the natural place to record who wrote a unit and from which config.
#: `service uninstall` refuses a file that lacks them.
MARKER_KEY = "X-Siteloom-Generator"


def _quote(value: str) -> str:
    """systemd's own quoting for a command-line word.

    `ExecStart=` is not a shell line, but it is not a raw string either:
    a path with a space is two arguments unless it is quoted, and
    backslashes and quotes inside need escaping. A config living under
    "/Users/me/My Site/" is an ordinary thing on macOS and a broken unit
    here without this.
    """
    if value and not any(c in value for c in ' \t\n"\'\\'):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _argv(argv: list[str]) -> str:
    return " ".join(_quote(part) for part in argv)


def unit_dir(scope: str) -> Path:
    """Where systemd looks for units at this scope.

    User units follow the XDG base directory spec — that is systemd's
    own rule, not a preference. Note that only the *unit file* is placed
    by XDG: logs and state stay wherever the config says, because two
    mechanisms deciding where `media_dir` lives is the CLD-64 bug.
    """
    if scope == "system":
        return Path("/etc/systemd/system")
    base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / "systemd" / "user"


def unit_path(spec: ServiceSpec) -> Path:
    return unit_dir(spec.scope) / f"{spec.label}.service"


def render(spec: ServiceSpec) -> str:
    lines = [
        f"# Generated by `siteloom service install` ({spec.generator}).",
        "# Edit the `service:` section of the config and re-run install;",
        "# `siteloom service print-unit` shows this without writing it.",
        "#",
        "# WorkingDirectory is load-bearing, not cosmetic: storage.db_url is a",
        "# URL rather than an anchored path, so a relative sqlite:/// database",
        "# resolves against it.",
        "#",
        "# Do not add --workers: the embedded Qdrant vector store allows one",
        "# client per path per machine, so a second worker cannot open it.",
        "",
        "[Unit]",
        f"Description={spec.description}",
        "Documentation=https://github.com/georgeevil/Siteloom/blob/main/docs/operations.md",
        f"X-Siteloom-Unit={spec.unit}",
        f"X-Siteloom-Config={spec.config_path}",
        f"X-Siteloom-Site={spec.site_id}",
        f"{MARKER_KEY}={spec.generator}",
    ]
    if spec.scope == "system":
        # A *user* manager has no network-online.target to wait on, so
        # emitting it there is cargo cult. Even at system scope this is a
        # nicety: the ingest loop already backs off and reconnects.
        lines += ["Wants=network-online.target", "After=network-online.target"]
    if spec.restart != "never":
        # StartLimit* belong to [Unit], not [Service] — they have since
        # systemd 229, and a unit that puts them under [Service] gets a
        # warning and no rate limit. Without a brake, a config error
        # respawns forever at full speed.
        lines += [
            f"StartLimitIntervalSec={spec.start_limit_interval_s}",
            f"StartLimitBurst={spec.start_limit_burst}",
        ]
    lines += [
        "",
        "[Service]",
        # `exec` rather than `simple` so a bad venv path or a missing
        # config is reported as a failed start instead of a start that
        # succeeded and a process that vanished. `notify` is opt-in and
        # only for `serve` — see notify.py for why it is not the default.
        f"Type={'notify' if spec.notify else 'exec'}",
        f"WorkingDirectory={spec.working_dir}",
    ]
    for key, value in spec.environment.items():
        lines.append(f'Environment="{key}={value}"')
    if spec.preflight:
        # `doctor` is documented as safe to run at any time and exits
        # non-zero only on a real failure, so it gates a boot into a
        # broken deployment without ever blocking a healthy one.
        lines.append(f"ExecStartPre={_argv(spec.preflight)}")
    lines.append(f"ExecStart={_argv(spec.program)}")
    if spec.restart != "never":
        lines += [f"Restart={spec.restart}", f"RestartSec={spec.restart_delay_s}"]
    if spec.success_exit_status:
        # `siteloom jobs cancel` exits 130 by design. Without this,
        # Restart=on-failure reads a deliberate cancel as a crash and
        # brings the job the operator just stopped straight back.
        lines.append(
            "SuccessExitStatus="
            + " ".join(str(code) for code in spec.success_exit_status)
        )
    lines.append(f"TimeoutStopSec={spec.stop_timeout_s}")
    if spec.notify:
        lines.append("NotifyAccess=main")
    lines += [
        "",
        "# KillSignal and KillMode are deliberately absent: the defaults",
        "# (SIGTERM, control-group) are already right. SIGTERM is handled",
        "# exactly like Ctrl-C, and ingest's workers are threads rather than",
        "# child processes, so KillMode=mixed would buy nothing.",
        "NoNewPrivileges=yes",
        "PrivateTmp=yes",
        # `full` rather than `strict`: strict makes everything read-only
        # except an enumerated list, and one missing path fails minutes
        # into a run instead of at start. ReadWritePaths below is emitted
        # regardless so that tightening this to `strict` by hand is a
        # one-word edit rather than an archaeology exercise.
        "ProtectSystem=full",
        "# ProtectHome is not set: the face weights cache lives in the",
        "# operator's home (~/.cache/siteloom/models) unless",
        "# SITELOOM_MODELS_DIR moves it.",
    ]
    if spec.read_write_paths:
        lines.append(
            "ReadWritePaths=" + " ".join(_quote(str(p)) for p in spec.read_write_paths)
        )
    if spec.run_as:
        lines.append(f"User={spec.run_as}")
    lines += [
        "",
        "[Install]",
        # A user unit under multi-user.target never starts.
        f"WantedBy={'multi-user.target' if spec.scope == 'system' else 'default.target'}",
        "",
    ]
    return "\n".join(lines)
